apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knot-resolver

resources:
  - base/deployment.yaml
  - base/svc.yaml
  - base/pdb.yaml

images:
  - name: danielkubat/knot-resolver-rpi
    newTag: 6.0.9-1  # https://github.com/danielkubat/knot-resolver-rpi/releases
