apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knot-resolver

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/svc.yaml
  - base/pdb.yaml

images:
  - name: danielkubat/knot-resolver-rpi
    digest: sha256:8ea4c1801b6dbedc5df8dbb460be2ef23550aa680a5ca3df4904529a0e175ddc  # https://github.com/danielkubat/knot-resolver-rpi/releases
