apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knot-resolver

resources:
  - deployment.yaml
  - svc.yaml
  - pdb.yaml

images:
  # https://github.com/danielkubat/knot-resolver-rpi/releases
  - name: danielkubat/knot-resolver-rpi
    newTag: 6.0.11-2
