version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "monthly"
