apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-operator

resources:
  # https://grafana.github.io/grafana-operator/docs/installation/kustomize/
  - https://github.com/grafana/grafana-operator/releases/download/v5.17.0/kustomize-cluster_scoped.yaml
