apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-data-pv
spec:
  claimRef:
    name: nodered-data-pvc
    namespace: nodered
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/k8s_data/nodered/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rd2pi
