apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-config-pvc
  namespace: nodered
  labels:
    app: nodered
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
