apiVersion: v1
kind: Service
metadata:
  name: nodered-svc
  namespace: nodered
spec:
  selector:
    app: nodered
  ports:
    - name: http
      port: 1880
      protocol: TCP
      targetPort: 1880
  type: LoadBalancer
