apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/danielkubat/kubernetes
        revision: main
        directories:
          - path: "*"
          - path: .github
            exclude: true
          - path: argocd
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/danielkubat/kubernetes
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          annotations:
            argocd.argoproj.io/tracking-id: >-
              {{path.basename}}:/Namespace:{{path.basename}}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
