apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: knot-resolver
  name: knot-resolver
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: knot-resolver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knot-resolver
    spec:
      containers:
        - name: knot-resolver
          image: danielkubat/knot-resolver-rpi
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
          resources:
            limits:
              memory: "200Mi"
            requests:
              cpu: "10m"
              memory: "200Mi"
