apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: knot-resolver
  name: knot-resolver
spec:
  selector:
    app.kubernetes.io/name: knot-resolver
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  type: LoadBalancer
