apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.prometheus.svc:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      timeInterval: 10s
      cacheLevel: 'Low'
      disableRecordingRules: false
      incrementalQuerying: true
