apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - resources/prometheus.yaml
  - svc.yaml
  - namespace.yaml
  - rbac.yaml

images:
  # https://github.com/prometheus/prometheus/releases
  - name: prom/prometheus
    newTag: v3.11.2
