apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/svc.yaml
  - base/pvc.yaml

images:
  - name: prom/prometheus
    newTag: v2.54.1  # https://github.com/prometheus/prometheus/releases

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-configuration
    files:
      - conf/prometheus.yaml
