apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - deployment.yaml
  - svc.yaml
  - pvc.yaml

images:
  # https://github.com/prometheus/prometheus/releases
  - name: prom/prometheus
    newTag: v3.4.1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-configuration
    files:
      - conf/prometheus.yaml
