apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: unbound
  name: unbound
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unbound
    spec:
      containers:
        - name: unbound
          image: danielkubat/unbound-rpi
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
          resources:
            limits:
              memory: "100Mi"
            requests:
              cpu: "10m"
              memory: "100Mi"
