apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: danielkubat/unbound-rpi
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
          resources:
            limits:
              memory: "50Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
