apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: unbound
  name: unbound
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
