apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: pihole
spec:
  selector:
    app: unbound
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  clusterIP: 10.43.53.53
