apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - base/deployment.yaml
  - base/svc.yaml
  - base/pvc.yaml

images:
  - name: pihole/pihole
    newTag: 2025.02.0  # https://github.com/pi-hole/docker-pi-hole/releases

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pihole-env
    literals:
      - TZ=Europe/Prague
      - FTLCONF_webserver_api_password=""
      - FTLCONF_dns_dnssec=false
      - FTLCONF_dns_upstreams=10.43.53.53#5335  # clusterIP from knot-resolver service
  - name: pihole-whitelist-configuration
    files:
      - conf/whitelist.txt
