apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/svc.yaml
  - base/pvc.yaml

images:
  - name: pihole/pihole
    newTag: 2024.06.0 # https://github.com/pi-hole/docker-pi-hole/releases

configMapGenerator:
  - name: pihole-env
    options:
      disableNameSuffixHash: true
    literals:
      - TZ=Europe/Prague
      - WEBPASSWORD=admin
      - DNSSEC=true
