apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - deployment.yaml
  - svc.yaml
  - pvc.yaml

images:
  # https://github.com/pi-hole/docker-pi-hole/releases
  - name: pihole/pihole
    newTag: 2025.07.1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pihole-env
    literals:
      - TZ=Europe/Prague
      - FTLCONF_webserver_api_password=""
      - FTLCONF_dns_dnssec=false
      - FTLCONF_dns_upstreams=10.43.53.53#5335  # knot-resolver clusterIP
  - name: pihole-whitelist-configuration
    files:
      - conf/whitelist.txt
