apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/svc.yaml
  - base/pvc.yaml

images:
  - name: pihole/pihole
    newTag: 2024.07.0  # https://github.com/pi-hole/docker-pi-hole/releases

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pihole-env
    literals:
      - TZ=Europe/Prague
      - WEBPASSWORD=""
      - DNSSEC=false
      - PIHOLE_DNS_=10.43.53.53#5335  # clusterIP from knot-resolver service
  - name: pihole-whitelist-configuration
    files:
      - conf/whitelist.txt
