apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/svc.yaml
  - base/pv.yaml
  - base/pvc.yaml

images:
  - name: oijkn/pihole-doh-dot
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pihole-env
    literals:
    - TZ=Europe/Prague                             # Set your timezone to make sure logs rotate at local midnight instead of at UTC midnight.
    - WEBPASSWORD=password                        # Set your password to access Web UI
    - ServerIP=0.0.0.0                            # Set to your server's LAN IP, used by web block modes and lighttpd bind address
    - PIHOLE_DNS_=127.0.0.1#5053;127.0.0.1#5153   # Upstream DNS server(s) for Pi-hole to forward queries to, seperated by a semicolon (supports non-standard ports with #[port number]) e.g 127.0.0.1#5053;8.8.8.8;8.8.4.4
    - IPv6=false                                  # For unraid compatibility, strips out all the IPv6 configuration from DNS/Web services when false.
    - DNSMASQ_LISTENING=all                       # local listens on all local subnets, all permits listening on internet origin subnets in addition to local, single listens only on the interface specified.
    - DNSMASQ_USER=root                           # Allows running FTLDNS as non-root.
