apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pihole
  name: pihole
spec:
  selector:
    app.kubernetes.io/name: pihole
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  type: LoadBalancer
