apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - base/namespace.yaml
  - resources/grafana-instance.yaml
  - resources/prometheus-datasource.yaml

images:
  - name: grafana/grafana
    newTag: 1.11.0 # https://github.com/grafana/grafana/releases
