apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - base/namespace.yaml
  - resources/grafana-instance.yaml
  - resources/prometheus-datasource.yaml
  - resources/node-exporter-dashboard.yaml

images:
  - name: grafana/grafana-oss
    newTag: 11.1.3 # https://github.com/grafana/grafana/releases
