apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - resources/grafana-instance.yaml
  - resources/prometheus-datasource.yaml
  - resources/node-exporter-dashboard.yaml
  - resources/ingress.yaml

images:
  - name: grafana/grafana-oss
    newTag: 11.6.0  # https://github.com/grafana/grafana/releases
