apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - resources/grafana-instance.yaml
  - resources/prometheus-datasource.yaml
  - resources/node-exporter-dashboard.yaml

images:
  # https://github.com/grafana/grafana/releases
  - name: grafana/grafana-oss
    newTag: 12.0.0
