apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/svc.yaml
  - base/pvc.yaml

images:
  - name: grafana/grafana-oss
    newTag: 11.0.0 # https://github.com/grafana/grafana/releases

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-env
    literals:
      - GF_NEWS_NEWS_FEED_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
  - name: prometheus-datasource
    files:
      - conf/prometheus-datasource.yaml
