apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    app.kubernetes.io/name: cadvisor
spec:
  selector:
    app.kubernetes.io/name: cadvisor
  ports:
    - name: http
      port: 8100
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
