apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate  
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yaml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.retention.time=180d"
          - "--storage.tsdb.retention.size=5GB"
        ports:
          - containerPort: 9090
            name: http
            protocol: TCP
        resources:
          limits:
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "100Mi"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
          - name: prometheus-configuration
            mountPath: /etc/prometheus
          - name: prometheus-persist-data
            mountPath: /prometheus
      volumes:
        - name: prometheus-persist-data
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: prometheus-configuration
          configMap:
            name: prometheus-configuration
