apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: base  # shared CRDs
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.27.0
  releaseName: istio
  namespace: istio-system

- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.27.0
  releaseName: istio
  namespace: istio-system

- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.27.0
  releaseName: istio-gateway
  namespace: istio-system
