global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: node_exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter.node-exporter:9100"]
