apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - base/namespace.yaml
  - base/install.yaml

patches:
  - target:
      version: v1
      kind: Service
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/ports/0/port # http
        value: 8090
      - op: remove
        path: /spec/ports/1 # https
      - op: add
        path: /spec/type
        value: LoadBalancer

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      # Run server without TLS
      - server.insecure=true
  - name: argocd-cm
    behavior: merge
    literals:
      # Polling a repository interval
      - timeout.reconciliation=600s
