apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-server
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: /argocd
      route:
        - destination:
            host: argocd-server
            port:
              number: 8090
