apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    app.kubernetes.io/name: grafana
    instance: grafana
  name: grafana
spec:
  config:
    auth:
      disable_login_form: "true"
    auth.anonymous:
      enabled: "true"
      org_role: "Admin"
    auth.basic:
      enabled: "false"
    analytics:
      enabled: "false"
    news:
      news_feed_enabled: "false"
    server:
      enable_gzip: "true"
  deployment:
    spec:
      replicas: 1
      strategy:
        type: RollingUpdate
      revisionHistoryLimit: 0
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana-oss
              resources:
                limits:
                  memory: "256Mi"
                requests:
                  cpu: "100m"
                  memory: "256Mi"
