apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cadvisor

resources:
  - base/daemonset.yaml
  - base/svc.yaml
  - base/serviceaccount.yaml

images:
  - name: gcr.io/cadvisor/cadvisor
    newTag: v0.49.2  # https://github.com/google/cadvisor/releases
