apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: chrony
  name: chrony
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: chrony
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chrony
    spec:
      hostNetwork: true
      containers:
        - name: chrony
          image: cturra/ntp
          envFrom:
            - configMapRef:
                name: chrony-env
          ports:
            - containerPort: 123
              name: ntp
              protocol: UDP
          resources:
            limits:
              memory: "50Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
