apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chrony

resources:
  - base/namespace.yaml
  - base/deployment.yaml

images:
  - name: cturra/ntp
    newTag: latest # https://github.com/cturra/docker-ntp

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: chrony-env
    literals:
      - NTP_SERVERS="217.31.202.100,195.113.144.201,195.113.144.238,147.229.9.10,193.0.0.229"
      - LOG_LEVEL=3
      - NOCLIENTLOG=true
      - TZ=Europe/Prague
