apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
spec:
  claimRef:
    name: homeassistant-config-pvc
    namespace: homeassistant
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/k8s_data/homeassistant/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rd2pi
