apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: argocd
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
