apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: argocd
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
