apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-unbound
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: unbound
    targetRevision: main
  destination:
    namespace: unbound
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=false
