apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 02-ingress-nginx
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: ingress-nginx
    targetRevision: main
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
