apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 03-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: grafana
    targetRevision: main
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
