apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 04-knot-resolver
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: knot-resolver
    targetRevision: main
  destination:
    namespace: knot-resolver
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=false
