apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 04-prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: prometheus
    targetRevision: main
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=false
