apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 06-prometheus
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: prometheus
    targetRevision: main
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: prometheus
