apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 09-cadvisor
  namespace: cadvisor
  labels:
    app.kubernetes.io/name: cadvisor
spec:
  project: default
  source:
    repoURL: https://github.com/danielkubat/kubernetes
    path: cadvisor
    targetRevision: main
  destination:
    namespace: cadvisor
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
