apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-exporter

resources:
  - base/namespace.yaml.yaml
  - base/deployment.yaml
  - base/svc.yaml

images:
  - name: prom/node-exporter
    newTag: v1.8.1 # https://github.com/prometheus/node_exporter/releases
