apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-exporter

resources:
  - base/daemonset.yaml
  - base/svc.yaml

images:
  # https://github.com/prometheus/node_exporter/releases
  - name: prom/node-exporter
    newTag: v1.9.1
