apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
  name: node-exporter
spec:
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - name: http
      port: 9100
      protocol: TCP
      targetPort: 9100
  type: ClusterIP
